# Chapter 4: NumPy Basics: Arrays and Vectorized Computation

NumPy objects operate as the *lingua franca* across computation packages for data

Provides data structures and algorithms required for most scientific applications
- ndarray: optimized multidimensional array
- Element-wise array functions or array binary operations
- Tools for reading / writing array-based datasets to disk
- Linear Algebra operations, Fourier transform, and random number generation

The areas of focus of this chapter include:
- Fast vectorized array operations
- Common array algorithms like sorting, unique, and set operations
- Effective descriptive statistics and aggregating/summarizing data
- Data alignment and relational data manipulations
- Expressing conditional logic as arrays instead of loops with if-elif-else
- Group-wise data manipulation (aggrefation, transformation, mapping, etc)

The reasons that NumPy is so much faster than Python is:
- NumPy stores data in a contiguous block of memory
- Numpy's library of algorithms is written in C and pre compiled
- NumPy can perform operations that would take typical Python loops without them

## 4.1. The NumPy ndarray: A Multidimensional Array Object

In [3]:
import numpy as np

Use the %time command to compare run times

In [4]:
my_arr = np.arange(10000)
my_list = list(my_arr)

%time for _ in range(10): my_arr2 = my_arr*2
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 256 µs, sys: 173 µs, total: 429 µs
Wall time: 369 µs
CPU times: user 11.8 ms, sys: 0 ns, total: 11.8 ms
Wall time: 11.7 ms


NumPy Operations

In [5]:
data = np.random.randn(2,3)
data

array([[-1.01302568,  0.90571103, -0.33980246],
       [-0.17956855,  3.40523712, -0.63161094]])

In [6]:
data*10

array([[-10.13025679,   9.05711033,  -3.3980246 ],
       [ -1.79568554,  34.05237121,  -6.31610944]])

In [7]:
data + data

array([[-2.02605136,  1.81142207, -0.67960492],
       [-0.35913711,  6.81047424, -1.26322189]])

Every array has a shape defined by a tuple indicating the size of each dimension

In [8]:
data.shape

(2, 3)

In [9]:
data.ndim

2

Each array also has a data type (dtype) describing the type of each element of
the array

In [10]:
data.dtype

dtype('float64')

### Creating ndarrays

`np.array` converts a python array-like and produces a NumPy array.

In [11]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

Also works for nested lists to create a multidim array

In [12]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

`np.array` infers a good data type for the array

In [15]:
arr1.dtype

dtype('int64')

In [16]:
arr2.dtype

dtype('int64')

`np.zeros` and `np.ones` create arrays of a given length / shape filled with 
only 0s or 1s respectively.

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

`np.empty` creates an array without initializing any of its values.

In [19]:
np.empty((2,3))

array([[2.02605136, 1.81142207, 0.67960492],
       [0.35913711, 6.81047424, 1.26322189]])

Finally, `np.arange` returns a list of values similar to Python's `range` function

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

Each of the array creation functions take an optional dtype parameter

NumPy supports the following data types:
- int8
- uint8
- int16
- uint16
- int32
- uint32
- int64
- uint64
- int128
- uint128
- float16
- float32
- float64
- float128
- float256
- complex64
- complex128
- complex256
- complex512
- bool
- object: reference to a Python object
- string_: fixed length ASCII string type 
- unicode_: fixed length unicode string type

Finally, `np.ndarray.astype` serves as a way to convert compatible arrays to a 
different type

In [21]:
arr = np.array([1.1,1.5,2.0,5.7,6.2])
arr.astype(np.int64)

array([1, 1, 2, 5, 6])

### Arithmetic with NumPy arrays

NumPy's arrays can be used for batch operations on data without loops.
This is caled *vectorization*.

Any arithmetic operations between equal sized arrays applies element-wise

In [22]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Comparisons between arrays return boolean arrays of the same size

In [27]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [28]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Operations between differently sized arrays is called broadcasting and is 
covered in Appendix A. This is not frequently necessary.

### Basic Indexing and Slicing

There are many ways to select a subset of an array

The most basic way is for 1-D arrays which act similar to Python lists

In [29]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[5]

5

In [31]:
arr[5:8]

array([5, 6, 7])

Unlike Python lists, you can assign a value to a slice, causing the value to be
broadcasted to the entire selection

In [32]:
arr[5:8] = 12

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Unlike Python, slices are views of the original array, not copies. Any 
modifications will be reflected in the source array.

In [33]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [34]:
arr_slice[1] = 12345

In [35]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

To force copying, use `np.ndarray.copy`

With higher dimensional arrays, we have so many more options. For instance, we 
have multiple indecies for each value

In [36]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The elements at each index are now 1-D arrays

In [37]:
arr2d[2]

array([7, 8, 9])

But we can access deeper elements either recursively or by passing a comma 
seperated list

In [38]:
arr2d[0][2]

3

In [39]:
arr2d[0,2]

3

We can assign both scalars and arrays to any of these values

In [40]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr3d[0] = 0
arr3d

array([[[ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d[0] = [[-1, -1, -1],[-1,-1,-1]]
arr3d

array([[[-1, -1, -1],
        [-1, -1, -1]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Indexing with slices

Each axis or dimension of the ndarray can be sliced like python lists

In [44]:
arr = np.array([np.arange(5), np.arange(5,10), np.arange(10,15)])
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
arr[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
arr[1:,3:]

array([[ 8,  9],
       [13, 14]])

In [47]:
arr[1,::2]

array([5, 7, 9])

### Boolean Indexing

Additionally, we can use an array of booleans to select elements of a same-sized
array

In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [49]:
data = np.random.randn(7,4)
data

array([[ 0.89891441, -0.09544347,  0.03119275,  0.27758147],
       [ 0.61339885,  0.41549287, -0.06982289,  2.05703736],
       [ 0.20447704, -0.07746085, -0.19132703, -0.4510985 ],
       [ 0.01705056,  0.94583476, -1.07641151, -0.53706179],
       [ 0.18223904,  0.16265719,  1.18206713,  0.54111015],
       [-0.53581263, -0.63044795,  0.26819993, -0.53786924],
       [-0.74282746, -0.6765332 , -0.24424308,  0.77336186]])

In [50]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [51]:
data[names=='Bob']

array([[ 0.89891441, -0.09544347,  0.03119275,  0.27758147],
       [ 0.01705056,  0.94583476, -1.07641151, -0.53706179]])

In [52]:
data[names=='Bob', 2:]

array([[ 0.03119275,  0.27758147],
       [-1.07641151, -0.53706179]])

We can use this boolean indexing to set all values of data < 0 to 0

In [53]:
data[data<0] = 0
data

array([[0.89891441, 0.        , 0.03119275, 0.27758147],
       [0.61339885, 0.41549287, 0.        , 2.05703736],
       [0.20447704, 0.        , 0.        , 0.        ],
       [0.01705056, 0.94583476, 0.        , 0.        ],
       [0.18223904, 0.16265719, 1.18206713, 0.54111015],
       [0.        , 0.        , 0.26819993, 0.        ],
       [0.        , 0.        , 0.        , 0.77336186]])

### Fancy Indexing

This is a way to index NumPy arrays by using integer arrays

In [54]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [55]:
arr[[4,3,0,6]]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [24, 25, 26, 27]])

You can even do it on multiple indicies.
The following code takes the first element of the 5th row, the 3rd element of the 3rd row etc

In [56]:
arr[[4,3,0,6], [0,3,2,1]]

array([16, 15,  2, 25])

In [57]:
arr[[4,3,0,6]][:, [0,3,2,1]]

array([[16, 19, 18, 17],
       [12, 15, 14, 13],
       [ 0,  3,  2,  1],
       [24, 27, 26, 25]])

Fancy indexing always copies the data into a new array

### Transposing Arrays and Swapping Axes

In [58]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

The T attribute returns the a view of the transpose of the array 

In [59]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

For higher dimensional arrays, transpose will take a tuple of axis numbers that
define the permutation order (rather than just swapping for 1/2D)

In [60]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [61]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

ndarray also has the method `swapaxes` which swaps two axes

In [62]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 4.2 Universal Functions: Fast Element-Wise Array Functions

A universal function or *ufunc*, is a function that performs element-wise
operations on data in ndarrays.

They are fast vectorized wrappers for simple functions

### Unary ufuncs

Single array functions like `sqrt` or `exp`

In [63]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [65]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### Binary unfuncs

Ex. `add` or `maximum`

In [66]:
x = np.random.randn(8)
y = np.random.randn(8)

In [67]:
x

array([ 0.25602656,  0.43300397, -0.68763077, -1.53793055,  0.30007024,
        0.39709388, -0.25609265,  1.21999002])

In [68]:
y

array([ 0.45779783, -1.38775931, -0.12594039, -0.23629946, -1.43742029,
       -0.28916722, -0.42819466, -0.18529986])

In [69]:
np.maximum(x,y)

array([ 0.45779783,  0.43300397, -0.12594039, -0.23629946,  0.30007024,
        0.39709388, -0.25609265,  1.21999002])

A unfunc can return multiple arrays: `modf` is an example

In [70]:
x = x* 5
x

array([ 1.28013278,  2.16501984, -3.43815386, -7.68965277,  1.50035121,
        1.98546941, -1.28046325,  6.09995009])

In [71]:
remainder, whole_part = np.modf(x)

`modf` splits a floating point into its integer and fractional parts

In [72]:
whole_part

array([ 1.,  2., -3., -7.,  1.,  1., -1.,  6.])

In [73]:
remainder

array([ 0.28013278,  0.16501984, -0.43815386, -0.68965277,  0.50035121,
        0.98546941, -0.28046325,  0.09995009])

Finally, unfuncs have an optional `out` parameter that allow it to act in place

In [74]:
x = np.arange(9, dtype=np.float64)
np.sqrt(x,x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [75]:
x

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

The list of unfuncs is as follows:

**Unary**
- abs
- fabs
- sqrt
- square
- exp
- log
- log10
- log2
- log1p
- sign
- ceil
- floor
- rint
- modf
- isnan
- isfinite
- isinf
- cos
- cosh
- sin
- sinh
- tan
- tanh
- arccos
- arccosh
- arcsin
- arcsinh
- arctan
- arctanh
- logical_not

**Binary**
- add
- subtract
- multiply
- divide
- floor_divide
- power
- maximum
- fmax
- minimum
- fmin
- mod
- copysign
- greater
- greater-equal
- less
- less-equal
- equal
- not_equal
- logical_and
- logical_or
- logical_xor

## 4.3 Array-Oriented Programming with Arrays

Using NumPy lets you express data processing tasks as array expressions rather
than loops. This provides a 10-100x speedup over vanilla Python. 

As an example, we will evaluate the function $\sqrt{x^2 + y^2}$ across a grid
of values

In [76]:
points = np.arange(-5, 5, 0.01)

In [77]:
xs, ys = np.meshgrid(points, points)

In [78]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

### Expressing Conditional Logic as Array Operations

`numpy.where` is a vectorized version of the expression `x if cond else y`

In [79]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

We then can take a value from xarr if cond is true and from yarr otherwise

In [80]:
result = list([(x if c else y) for x, y, c in zip(xarr, yarr, cond)])
result = np.where(cond, xarr, yarr)

np.where can also be passed a scalar

In [81]:
np.where(cond, 2, -2)

array([ 2, -2,  2,  2, -2])

### Mathematical and Statistical Methods

A set of mathematical functions are availiable that compute statistics about an
entire array or about an axis of the data. These aggregations like `sum`, `mean`,
and `std` are all called reductions

In [82]:
arr = np.random.randn(5,4)
arr

array([[-3.84399762e-01, -5.57520160e-04,  1.95362348e-01,
         2.17003534e+00],
       [-9.58442102e-01,  7.95534394e-02,  1.73464071e+00,
        -6.00331503e-01],
       [ 1.46286847e+00, -2.60300457e-01,  5.58626007e-01,
        -1.23144555e-01],
       [ 5.00968289e-01, -9.61922323e-01, -3.37119360e-01,
        -1.13574871e+00],
       [ 9.70759366e-01,  7.35608131e-02, -2.65312858e-01,
        -6.11502076e-01]])

In [83]:
arr.mean()

0.1053796779281491

In [84]:
np.mean(arr)

0.1053796779281491

In [85]:
arr.sum()

2.107593558562982

These functions also can take an axis argument that computes the statistic over 
the given axis

In [86]:
arr.mean(axis=1)

array([ 0.4951101 ,  0.06385514,  0.40951237, -0.48345553,  0.04187631])

In [87]:
arr.sum(axis=1)

array([ 1.9804404 ,  0.25542055,  1.63804946, -1.9338221 ,  0.16750525])

Some methods like `cumsum` and `cumprod` do not aggregate and instead produce
an array of intermediate results

In [88]:
arr = np.arange(1, 8)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [89]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

In [90]:
arr.cumprod()

array([   1,    2,    6,   24,  120,  720, 5040])

Basic array statistical functions:
- sum
- mean
- std
- var
- min
- max
- argmin
- argmax
- cumsum
- cumprod

### Methods for Boolean Arrays

`sum` counts the number of True values

In [91]:
arr = np.random.randn(100)
(arr > 0).sum()

40

Also, `any` returns True if any are True, and `all` returns True if all are True

In [92]:
bools = np.array([True, False, False, False])
bools

array([ True, False, False, False])

In [93]:
bools.any()

True

In [94]:
bools.all()

False

### Sorting

In [95]:
arr = np.random.randn(6)
arr

array([ 0.86156798, -2.34551523,  1.31598802, -0.66433795, -0.9519537 ,
       -0.37389232])

In [96]:
arr.sort()
arr

array([-2.34551523, -0.9519537 , -0.66433795, -0.37389232,  0.86156798,
        1.31598802])

In [97]:
arr = np.random.randn(6, 5)
arr

array([[-1.25370375,  0.0140747 , -1.1918967 ,  0.54123995, -0.91657191],
       [-0.78559334,  0.34879886, -0.92110123,  0.7962466 , -0.22421357],
       [ 0.60739499,  0.58608007,  1.34206635, -0.02188047,  0.52774343],
       [ 0.97102477, -0.5215701 ,  0.37774492,  0.14603788, -0.35502943],
       [-1.88417609,  0.38481774,  0.63064295, -0.892774  , -0.53830742],
       [-0.89559395, -1.03947212, -0.13208564, -0.53784872,  0.84681731]])

In [98]:
arr.sort(1)
arr

array([[-1.25370375, -1.1918967 , -0.91657191,  0.0140747 ,  0.54123995],
       [-0.92110123, -0.78559334, -0.22421357,  0.34879886,  0.7962466 ],
       [-0.02188047,  0.52774343,  0.58608007,  0.60739499,  1.34206635],
       [-0.5215701 , -0.35502943,  0.14603788,  0.37774492,  0.97102477],
       [-1.88417609, -0.892774  , -0.53830742,  0.38481774,  0.63064295],
       [-1.03947212, -0.89559395, -0.53784872, -0.13208564,  0.84681731]])

### Unique and Other Set Logic

In [99]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [100]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [101]:
np.in1d(names, ['Bob', 'Joe'])

array([ True,  True, False,  True, False,  True,  True])

Array set operations
- unique
- intersect1d
- union1d
- in1d
- setdiff1d
- setxor1d

## 4.4 File Input and Output with Arrays

NumPy is able to save and load data to and from disk in either text or binary.

This section will discuss binary saving, since pandas is likely to be used for
text or tabular data.

In [102]:
arr = np.arange(10)
#np.save('arr_name', arr)
#arr = np.load('arr_name.npy')

Can also store in an uncompressed archive

In [103]:
#np.savez('arr_archive.npz', a=arr, b=arr)
#arch = np.load('array_archive.npz')
#arr = arch['a']

Finally, can store in an compressed archive

In [104]:
#np.savez_compressed('arr_compressed.npz', a=arr, b=arr)
#arch = np.load('array_archive.npz')
#arr = arch['a']

## 4.5 Linear Algebra

NumPy has some simple linear algebra functions such as dot product, inverse, and qr

In [105]:
x = np.random.randn(5,5)
y = np.random.randn(5,5)
x

array([[ 1.1833294 ,  1.11316725,  0.30547459, -0.42103735,  0.95582644],
       [ 0.81410603, -0.09016089, -2.27636161, -0.04099304, -0.19040565],
       [-0.24885128, -0.66400758,  0.66416195,  0.06176408, -0.50538809],
       [-0.72728169, -0.58150944, -0.55934513, -2.24139066,  0.5301621 ],
       [ 1.00920943,  1.91082836,  0.80499245,  1.35237781,  0.01477749]])

In [106]:
y

array([[-1.11442216,  0.80217402,  0.1439962 ,  0.35854001,  2.14142745],
       [ 1.70080895,  0.03657901,  0.05508095,  1.92522771,  0.72916198],
       [-0.70507489,  0.16759188, -0.52241914,  0.14739183,  0.07484279],
       [ 0.08232771, -1.86909046, -0.07112755,  1.73894566, -0.12371856],
       [-1.13465554,  0.53445288, -0.42296971, -0.99625696, -0.77071379]])

In [107]:
np.dot(x,y)

array([[-0.76002296,  2.33895082, -0.3022148 ,  0.92798601,  2.68397739],
       [ 0.75707113,  0.24311385,  1.38492845, -0.09879948,  1.65905772],
       [-0.74178228, -0.49815139, -0.21000799, -0.65879611, -0.5854901 ],
       [-0.57023736,  3.77428936,  0.09063884, -5.88857483, -2.15460011],
       [ 1.65225947, -1.5054506 , -0.27241265,  6.49626032,  3.43599659]])

In [108]:
x.dot(y)

array([[-0.76002296,  2.33895082, -0.3022148 ,  0.92798601,  2.68397739],
       [ 0.75707113,  0.24311385,  1.38492845, -0.09879948,  1.65905772],
       [-0.74178228, -0.49815139, -0.21000799, -0.65879611, -0.5854901 ],
       [-0.57023736,  3.77428936,  0.09063884, -5.88857483, -2.15460011],
       [ 1.65225947, -1.5054506 , -0.27241265,  6.49626032,  3.43599659]])

The more advanced linear algebra functions are in `numpy.linalg`

In [113]:
from numpy.linalg import inv, qr

In [111]:
mat = x.T.dot(x)
mat

array([[ 3.6724064 ,  3.76042932, -0.43779277,  2.44798619,  0.73115001],
       [ 3.76042932,  5.67759463,  1.96774139,  3.38155087,  1.13668633],
       [-0.43779277,  1.96774139,  6.67712783,  2.34808501,  0.10510543],
       [ 2.44798619,  3.38155087,  2.34808501,  7.03552553, -1.59416379],
       [ 0.73115001,  1.13668633,  0.10510543, -1.59416379,  1.48656584]])

In [114]:
inv(mat)

array([[ 1.94801868, -0.76608711,  0.66514499, -0.82773617, -1.30700603],
       [-0.76608711,  1.51439827, -0.20934236, -0.74649591, -1.56690332],
       [ 0.66514499, -0.20934236,  0.41010396, -0.41229773, -0.63820815],
       [-0.82773617, -0.74649591, -0.41229773,  1.52537951,  2.64284999],
       [-1.30700603, -1.56690332, -0.63820815,  2.64284999,  5.39290608]])

In [117]:
q, r = qr(mat)
q

array([[-0.6266296 ,  0.30920586, -0.38899688,  0.56424574, -0.20502503],
       [-0.64164911, -0.32473248,  0.61938247, -0.19694121, -0.24579412],
       [ 0.0747014 , -0.88496741, -0.32954274,  0.30435391, -0.10011327],
       [-0.41770448, -0.10100226, -0.51634519, -0.61387113,  0.41457375],
       [-0.1247575 , -0.07464437,  0.29972656,  0.41637944,  0.8459645 ]])

In [118]:
r

array([[-5.86056965, -7.4067259 , -1.48339311, -6.26823111, -0.69923337],
       [ 0.        , -2.84873113, -6.92840557, -3.01075508, -0.1860076 ],
       [ 0.        ,  0.        , -1.99223396, -3.74215302,  1.65369386],
       [ 0.        ,  0.        ,  0.        , -3.55273514,  1.81826372],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.15686617]])

List of commonly used `numpy.linalg` functions
- diag
- dot
- trace
- det
- eig
- inv
- pinv
- qr
- svd
- solve
- lstsq

## 4.6 Pseudorandom Number Generation

The `numpy.random` module supplements the built-in `random` with functions for
generating whole arrays of values from distributions

In [120]:
samples = np.random.normal(size=(4,4))
samples

array([[ 1.05565393,  0.80433141,  0.80841356,  0.30206947],
       [ 0.63445455, -0.70902441,  0.00704157, -0.11605216],
       [-0.34412574,  0.33794844,  0.24185023, -0.67474861],
       [-0.5231382 ,  0.25567877,  1.09000345,  0.00317421]])

You can use `np.random.RandomState` to set a random number generator seperate
from others

In [121]:
rng = np.random.RandomState(12345)
rng.randn(10)

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474])

Partial list of `numpy.random` functions
- seed
- permutation
- shuffle
- rand
- randint
- randn
- binomial
- normal
- beta
- chisquare
- gamma
- uniform

## 4.7 Example: Random Walk

Using numpy, we will simulate many simultaneous 1d random walks

In [124]:
nwalks = 5000
nsteps = 1000

rand = np.random.randint(0, 2, size=(nwalks, nsteps))
rand

array([[0, 1, 1, ..., 0, 1, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 1]])

In [125]:
steps = np.where(rand > 0, 1, -1)
steps

array([[-1,  1,  1, ..., -1,  1, -1],
       [ 1, -1,  1, ..., -1, -1, -1],
       [ 1, -1,  1, ...,  1, -1, -1],
       ...,
       [-1,  1, -1, ...,  1,  1, -1],
       [ 1, -1, -1, ...,  1,  1, -1],
       [-1, -1, -1, ...,  1, -1,  1]])

In [127]:
cum_walks = np.cumsum(steps, axis=1)
cum_walks

array([[ -1,   0,   1, ...,  60,  61,  60],
       [  1,   0,   1, ...,  22,  21,  20],
       [  1,   0,   1, ..., -12, -13, -14],
       ...,
       [ -1,   0,  -1, ...,  20,  21,  20],
       [  1,   0,  -1, ..., -16, -15, -16],
       [ -1,  -2,  -3, ..., -70, -71, -70]])

In [128]:
cum_walks.max()

128

In [129]:
cum_walks.min()

-134

In [ ]:
cum_walks.mean()

-0.1311796

Now we will try and compute the crossing time for 30 or -30

In [131]:
hits30 = (np.abs(cum_walks) >= 30).any(1)
hits30

array([ True, False,  True, ..., False,  True,  True])

In [132]:
hits30.sum()

3379

In [135]:
crossing_times = (np.abs(cum_walks[hits30]) >= 30).argmax(1)
crossing_times

array([297, 607, 987, ..., 239, 423, 591])

In [136]:
crossing_times.mean()

503.25865640722105

## 4.8 Conclusion